const languageTemplate = {
  en: {
    currentTime: 'Current Time',
    todayWeather: 'Today Weather',
    feelsLike: 'feels like',
    wind: 'wind',
    speed: 'm/s',
    humidity: 'humidity',
    exchange: 'Exchange Rate',
    EUR: 'EUR',
    USD: 'USD',
    RUB: 'RUB',
    lng: 'Longitude',
    lat: 'Latitude',
    zoom: 'Zoom',
    searchPlaceholder: 'Search',
    designedBy: 'Designed by',
  },
  ru: {
    currentTime: 'Текущее Время',
    todayWeather: 'Погода Сегодня',
    feelsLike: 'ощущается',
    wind: 'ветер',
    speed: 'м/c',
    humidity: 'влажность',
    exchange: 'Курсы Валют',
    EUR: 'Евро',
    USD: 'Доллар',
    RUB: 'Рубль',
    lng: 'Долгота',
    lat: 'Широта',
    zoom: 'Масштаб',
    searchPlaceholder: 'Поиск',
    designedBy: 'Разработано',
  },
  pl: {
    currentTime: 'Obecny Czas',
    todayWeather: 'Dzisiejsza Pogoda',
    feelsLike: 'czuje się jak',
    wind: 'wiatr',
    speed: 'm/s',
    humidity: 'wilgotność',
    exchange: 'Kurs wymiany',
    EUR: 'EUR',
    USD: 'USD',
    RUB: 'RUB',
    lng: 'Długość geograficzna',
    lat: 'Szerokość',
    zoom: 'Powiększenie',
    searchPlaceholder: 'Szukaj',
    designedBy: 'Zaprojektowany przez',
  },
};

const getPhrase = (language, phrase) => languageTemplate[language][phrase];
export default getPhrase;
